### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by Mullebrouck** [Mullebrouck/SVTechsol#1]
- [x] Create Homepage in HTML with Navigation
- [x] Create Pages for website
- [x] Link Pages into Navigation
